[package]
name = "rust_with_linked_lists"
version = "0.1.0"
authors = ["iansudderth <ian.sudderth@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
